  version: 2
  updates:
    # Enable version updates for go
    - package-ecosystem: "gomod"
      directory: "/"
      schedule:
        interval: "daily"

    # Enable version updates for Docker
    - package-ecosystem: "docker"
      directory: "/"
      schedule:
        interval: "daily"