---
kind: pipeline
name: default

steps:
  - name: build & test
    image: golang
    commands:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.37.1
      - make build
      - make lint
      - make test