---
kind: pipeline
name: default

steps:
  - name: build & test
    image: golang
    commands:
      - go get honnef.co/go/tools/cmd/staticcheck
      - go get golang.org/x/tools/cmd/goimports
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.37.1
      - go get -u golang.org/x/lint/golint
      - make build
      - golangci-lint run
      - golint ./...
      - make fmt
      - make test