---
kind: pipeline
name: default

steps:
  - name: build & test
    image: docker
    commands:
      - apt-get install go
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.37.1
      - make build
      - make lint
#      - apt-get install docker-ce docker-ce-cli containerd.io
      - make test
      - get github.com/schrej/godacov
      - godacov -t $CODACY_TOKEN -r ./c.out -c ${DRONE_COMMIT}